### ISSUE TITLE
Create and populate listview with active session info

### ISSUE THREAD

**Issue by nsjake** [JakeNarkizian/sound-send#17]
Listeners will need to scroll through a list view of all the active sessions. I imagine the best implementation is a specific URL at the server's address returns some list of the currently active sessions. The client app sends an HTTP GET request for that list at the URL, gets and parses the response, and then populates some list view on the iDevice. 

If you go with this approach please comment bellow on what format you choose for the iOS app to parse so that @seant2g0 and I can implement it on the server-side.  For unit tests hard code one of these strings and feed it into your code. Make sure to cover any edge cases you can think of e.g. there are no current active sessions, there's only one active session, there' too many active sessions...  

If you decide to go with another approach please comment it below with your reasoning. Be sure to include any server-side dependencies of the new approach so that the backend team can start working on it.

**Comment by nsjake** [comment]
@adgupta @sejalchadha which one of you wants to take this one? Remember only one person can take on an issue at a time even if there is collaboration.

**Comment by sejalchadha** [comment]
@JakeNarkizian I have this one, thanks :)

**Comment by nsjake** [comment]
@sejalchadha I'm starting on the backend compliment of this functionality.  I'm thinking pinging a url like `http://baseurl.com/channelmanager/active` should return a list active channels in some format. What format do you think is easiest for you to implement on the ios side?

**Comment by nsjake** [comment]
@sejalchadha per conversation with @seant2g0 this issue will be taken over by him.

**Comment by seant2g0** [comment]
Hey can you comment on this diagram and write the changes in it
[Program Flow Diagram-1.docx](https://github.com/JakeNarkizian/sound-send/files/582558/Program.Flow.Diagram-1.docx)
[Description of Program Flow.txt](https://github.com/JakeNarkizian/sound-send/files/582559/Description.of.Program.Flow.txt)
