### ISSUE TITLE
Create database schema for storing session info

### ISSUE THREAD

**Issue by nsjake** [JakeNarkizian/sound-send#7]
We need a database to store info about all the sessions. 

Sejal is taking this one.

**Comment by nsjake** [comment]
Storing session data in-memory instead of in a SQL database is superior. Using a database introduces I/O costs and does not provide any apparent benefit. This issue is no longer necessary. 

At this point we can commit the scheme we have under a backlog subdirectory or close this issue outright. @sejalchadha since you worked on this I'll let you make the call.

**Comment by nsjake** [comment]
@sejalchadha I haven't heard from you, If you don't object within the next day or so I'm going to just close this issue.

**Comment by sejalchadha** [comment]
@JakeNarkizian Hi Jake, sorry for the late reply, didn't get notifications for this post- lets just close this out since we won't be using it all.
